//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITSM_Webservice.BusinessEntities.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionLogResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionLogResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITSM_Webservice.BusinessEntities.Exceptions.ExceptionLogResource", typeof(ExceptionLogResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} has invalid value &quot;{1}&quot;. Please provide an appropriate value {2}..
        /// </summary>
        internal static string ExceptionInvalidData {
            get {
                return ResourceManager.GetString("ExceptionInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITSM_WS_002.
        /// </summary>
        internal static string ExceptionInvalidDataCode {
            get {
                return ResourceManager.GetString("ExceptionInvalidDataCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} is empty. Please provide a value..
        /// </summary>
        internal static string ExceptionNullData {
            get {
                return ResourceManager.GetString("ExceptionNullData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITSM_WS_001.
        /// </summary>
        internal static string ExceptionNullDataCode {
            get {
                return ResourceManager.GetString("ExceptionNullDataCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remedy API Exception : {0}.
        /// </summary>
        internal static string ExceptionRemedyAPI {
            get {
                return ResourceManager.GetString("ExceptionRemedyAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITSM_WS_003.
        /// </summary>
        internal static string ExceptionRemedyAPICode {
            get {
                return ResourceManager.GetString("ExceptionRemedyAPICode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} in Method {1}.
        /// </summary>
        internal static string LogMethodStatus {
            get {
                return ResourceManager.GetString("LogMethodStatus", resourceCulture);
            }
        }
    }
}
